name: Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --filename=*.py Python/ --count --show-source --statistics --ignore=E501 --exit-code=0
    - name: Test with pytest
      run: |
        pip install pytest
        cd Python && pytest
